# Generated by Django 6.0.2 on 2026-02-09 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_provider', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['auth_provider'], name='idx_users_auth_provider'), models.Index(fields=['created_at'], name='idx_users_created_at')],
            },
        ),
    ]
