# Generated by Django 6.0.2 on 2026-02-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_is_permanent_user_is_guest_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
