# Generated by Django 6.0.2 on 2026-02-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('scientific_name', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalCharacteristic',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('prey', models.TextField(blank=True, null=True)),
                ('gestation_period', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('predators', models.TextField(blank=True, null=True)),
                ('average_litter_size', models.TextField(blank=True, null=True)),
                ('top_speed', models.TextField(blank=True, null=True)),
                ('lifespan', models.TextField(blank=True, null=True)),
                ('weight', models.TextField(blank=True, null=True)),
                ('length', models.TextField(blank=True, null=True)),
                ('skin_type', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('age_of_sexual_maturity', models.TextField(blank=True, null=True)),
                ('age_of_weaning', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_characteristics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalLocation',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('h3_index', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('count', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'animal_locations',
                'managed': False,
            },
        ),
    ]
