# Generated by Django 6.0.2 on 2026-03-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animalcharacteristic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='animallocation',
            options={},
        ),
    ]
