# Generated by Django 6.0.2 on 2026-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='high_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
