# Generated by Django 6.0.2 on 2026-03-01 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_auth_provider'),
        ('game', '0002_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_rooms', to='authentication.user'),
        ),
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_permanent_player', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_data', to='game.room')),
            ],
            options={
                'db_table': 'multiplayer_games',
            },
        ),
    ]
