# Generated by Django 6.0.2 on 2026-03-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_room_host_multiplayergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='score_awarded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
